# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r_packages:
  - covr
  - pkgdown
warnings_are_errors: true
sudo: false
cache: packages
os:
- linux
- osx
matrix:
  include:
  - r: devel
  - r: release
    after_success: Rscript -e 'covr::codecov()'
  - r: oldrel
  - r: 3.3
before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
git:
   depth: 9999999
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
